---
title: "diplo_diet"
output: html_document
date: "2025-03-25"
---

```{r, echo=F}
knitr::opts_chunk$set(echo = F, error = F, warning = F, fig.align="center", 
                      out.width = "90%", out.height = "50%", fig.height=5)

lapply(c("tidyverse", "data.table", "paletteer", "ggpubr", "ggtext", #"gplots", "R3port", 
         "xtable", "knitr", "tinytex", "emmeans"),  library, character.only = TRUE)

lapply(list.files("../../pantry/functions/", full.names = T), source)
palettes_pantry = palettes
source("../scripts/pantry.R", echo=F)

```

```{r}
###################################
##   Load data for EUR ancestry  ##
###################################

# system arguments
EUR=c("European"="EUR")
tag="v6"

# load postprocessed dataframe
postprocessed <- readRDS("../data/processed/ukb_postprocessed_EUR_20241227.rda")

analysis <- readRDS(paste0("../data/processed/ukb_analysis_EUR.rda"))
range(analysis$glu) #: 2.116 - 8.002
  
#load dietPCs
dietPCs.dat <- readRDS(paste0("../data/processed/diet/ukb_EUR_dietPCs.rda"))
dietPC_emm <- read.csv(paste0("../data/processed/descr_tab_emm_dietPC_diplos_sexageac_", tag,".csv"))
dietPC_pstat <- read.csv(paste0("../data/processed/descr_tab_teststat_dietPC_diplos_sexageac_",tag,".csv"))

taste_diplos.labs <- c("AVI/AVI", "AVI/PAV", "PAV/PAV")
taste_diplos <- c("AVI/AVI", "AVI/PAV", "PAV/PAV")
taste_diplos_005.labs <- c(taste_diplos.labs, "AVI/AAV", "AAV/PAV")

## Add glucose values with mg/dl
analysis <- analysis %>% mutate(
  glu_mgdl = glu*18.018,
  glu2hr_mgdl = glu2hr*18.018)

## Load preference traits
prefs_id <- fread("../../tasteprefs/data/raw/ukbb_app27892_diet_preference_11062024.csv") %>%
  rename(id=eid, survey_date=p20750, survey_duration=p20751) %>%
  filter(!is.na(survey_date)) %>% # filter out participants without preference data (N=320071)
  mutate(across(starts_with("p"), ~as.numeric(
    case_when(
    . %in% c(1:10) ~ as.character(.),
    . == "extremely dislike" ~ "1",
    . == "neither like nor dislike" ~ "5",
    . == "extremely like" ~ "9",
    . %in% c("never tried", "do not wish to answer") ~ "NA",
    TRUE ~ as.character(NA) ) ))
  ) 

codebook <-readxl::read_xlsx("../../tasteprefs/data/raw/food_pref_vars.xlsx") %>%
  mutate(var_name = gsub("Liking_for", "pref", gsub("/", "", gsub("[(]", "", gsub("[)]", "", gsub("-","", gsub(" ", "_", description)))))))

prefs_id <- prefs_id %>%
  rename_with(
    ~with(codebook, var_name[match(., paste0("p", fieldID))]),
    starts_with("p")
  )

analysis <- left_join(analysis, prefs_id, by="id")

sex.l <- c("Female", "Male")

```


```{r}

# ===================================
## Intake variables
# ===================================

diet_labels <- c(
  raw_veg_QT="Raw vegetables",
  cooked_veg_QT="Cooked vegetables",
  fresh_fruit_QT="Fresh fruit",
  dried_fruit_QT="Dried fruit",
  oily_fish_QT="Oily fish",
  nonoily_fish_QT="Non-oily fish",
  procmeat_QT="Processed meat",
  poultry_QT="Poultry",
  cheese_QT="Cheese",
  beef_QT="Beef",
  lamb_QT="Lamb",
  pork_QT="Pork",
  bread_type_white_vs_brown_or_whole_BIN="Prefer white bread",
  bread_intake_QT="Bread",
  milk_type_full_vs_low_or_nonfat_BIN="Prefer full-fat milk",
  cereal_type_sugar_vs_any_bran_BIN="Prefer sugary cereal",
  coffee_type_decaf_vs_regular_BIN="Prefer decaf coffee",
  cereal_intake_QT="Cereal",
  spread_type_butter_vs_any_other_BIN="Prefer butter>oil",
  coffee_QT="Coffee",
  tea_QT="Tea",
  water_QT="Water",
  addsalt_always_often_vs_nrs_BIN="Often add salt",
  hotdrink_temp_hot_or_vhot_vs_warm_BIN="Prefer hot drinks"
)


# ===================================
## Preference variables
# ===================================

pref_labels <- c(
  codebook %>% filter(var_name %in% names(analysis %>% select(starts_with("pref")))) %>% 
    arrange(description) %>% pull(description)
) ; names(pref_labels) = names(analysis %>% select(starts_with("pref")))

```

```{r}

genotype_dist_theme <- ggtheme_fancy +
    theme(axis.text.x = element_text(size=8, color = "black", face="italic"), #angle=25, hjust=1, 
          axis.text.y = element_text(size=8, color = "black"),
          axis.title.x = element_markdown(),
          axis.title = element_text(color = "black", face = "bold", size=10),
          
          legend.position = "inside",
          legend.text = element_text(size=8), legend.title=element_blank(),
          legend.position.inside = c(0.99, 0.98),  # Moves legend to top-right inside plot
          legend.justification.inside = c(1, 1),  # Aligns legend's top-right corner
          legend.background = element_rect(fill = "white", color = "black", linewidth=0.15), 
          
          legend.key.size = unit(1, 'line'),
          legend.margin = margin(3,3,3,3, unit="pt"),
          
          )  # Optional: Add background
  

# ================================
## Summary of haplotypes, by Sex
# ================================

## haplo_legend
pal_haplo_legend <- c(palettes$nature_haplos_dominant)[c(1,3:4)]
names(pal_haplo_legend) <- paste(c("Nontaster", "Taster", "Non-canonical"), "haplotype")

plot_haplos_AA.l <- lapply(sex.l, function(x) {
 tab_haplos_AA <- analysis %>%
    filter(sex==x) %>%
    select(id, haplo_0_aa, haplo_1_aa) %>%
    pivot_longer(-id, values_to="haplo") %>%
    group_by(haplo) %>% reframe(n=n(), pct=(n()/nrow(.))*100) %>%
    arrange(n) %>% mutate(haplo_order = factor(haplo, levels=haplo[order(n, decreasing = T)])) %>%
    mutate(diplo_legend = factor(ifelse(haplo_order == "AVI", "Nontaster haplotype", 
                                        ifelse(haplo_order == "PAV", "Taster haplotype", "Non-canonical haplotype")), 
                                 levels=paste(c("Nontaster", "Taster", "Non-canonical"), "haplotype"))) %>%
    #Filter to "common" haplotypes (>1% of the cohort; >0.005, frequency)
    filter(pct>0.05) ; tab_haplos_AA %>% 
    ggplot(aes(x=haplo_order, y=pct, fill=diplo_legend)) + 
    geom_bar(stat = "identity") + 
    scale_x_discrete(name = "**_TAS2R38_ Haplotype**") + 
    scale_y_continuous(limits=c(0,62), breaks=seq(0,60,10)) +
    ylab("Frequency (%)") + 
    scale_fill_manual(values = pal_haplo_legend, name=expression(italic("TAS2R38") ~ "Haplotypes (n)")) + 
   genotype_dist_theme +
    geom_text(aes(label=n), vjust=-0.35, size=3.0)
})

# ================================
## Summary of Diplotypes
# ================================
## Create variable in analysis for **common diplotypes**
diplos_gt005_AA <- names(which(prop.table(table(analysis$diplos_common_AA))>0.005))
analysis <- analysis %>% mutate(
  diplos_AA = factor(ifelse(diplos_common_AA %in% diplos_gt005_AA, diplos_common_AA, NA), levels=c(diplos_gt005_AA)))

## diplo_legend
pal_diplo_legend <- c(palettes$nature_diplos_dominant)[c(1,3:5)]
names(pal_diplo_legend) <- paste(c("Nontaster", "Taster", "Supertaster", "Non-canonical"), "diplotype")

## Table
plot_diplos_AA.l <- lapply(sex.l, function(x) { 
  tab_diplos_AA <- analysis %>% 
    filter(complete.cases(diplos_AA)) %>% #diplos_common_AA %in% diplos_common_AA) %>% 
    group_by(sex) %>%
    reframe(n=table(diplos_AA), pct=prop.table(table(diplos_AA)), diplos_AA=names(table(diplos_AA))) %>%
    arrange(-n) %>% 
    mutate(color = factor(ifelse(diplos_AA == "AVI/AVI", "Nontaster",
                                   ifelse(diplos_AA == "AVI/PAV", "Taster",
                                          ifelse(diplos_AA == "PAV/PAV", "Supertaster", "Non-canonical"))),
                            levels=c("Nontaster","Taster","Supertaster","Non-canonical"))) %>%
    mutate(diplos_AA_order=factor(diplos_AA, levels=c("AVI/AVI", "AVI/PAV", "PAV/PAV", "AVI/AAV", "AAV/PAV")),
           diplo_legend = factor(paste(color, "diplotype"), levels=
                                   paste(c("Nontaster","Taster","Supertaster","Non-canonical"), "diplotype"))) %>%
    filter(pct>0.005) 
  
  tab_diplos_AA %>%
    ggplot(aes(x=diplos_AA_order, y=pct*100, fill=diplo_legend, group=sex)) + 
    geom_bar(stat = "identity", position=position_dodge2(c(0.8,0.2)), width=0.75) + 
    scale_x_discrete(name = "**_TAS2R38_ Diplotypes**") + 
    scale_y_continuous(limits=c(0,52), breaks=seq(0,50,10)) + ylab("Frequency (%)") + 
    scale_fill_manual(values = pal_diplo_legend, name=expression(italic("TAS2R38") ~ "Diplotypes (n)")) + 
    genotype_dist_theme #+
    #geom_text(aes(label=n), vjust=-0.35, size=3.0)
})
  
plot_diplo_AA.l #%>% ggsave(filename=paste0("../output/descr_plot_diploAA005_order2_",tag,".pdf"), height = 4, width=6)

ggarrange(plotlist = plot_diplos_AA.l, nrow=1)
#
```

```{r}

palette_sex <- palettes$NatMainAccent3$Level3

dietsex <- fread("../data/processed/briefcomm/beta_diplo_diet_sex.csv") %>% select(diet=model, beta, se, p, sex)
diettot <- fread("../data/processed/briefcomm/beta_diplo_diet_mBase_total.csv") %>% select(diet=DietLabel, beta=Beta, se=SE, p=P_val_t) %>% mutate(sex="Total")
dietcomnp <- rbind.data.frame(dietsex, diettot)

p_diet_bysex <- dietcomnp %>% 
  group_by(diet) %>%
  mutate(sex = factor(sex, levels=c("Total", "Female", "Male"))) %>%
  arrange(p) %>%
  mutate(diet=factor(diet, levels=unique(diet[order(p)]))) %>%
  ggplot(aes(x=diet, y=beta, ymin=beta-1.96*se, ymax=beta+1.96*se, color=sex)) +
  geom_hline(yintercept = 0, color="black", linewidth=0.35) +
  geom_point(size=1.15, position = position_dodge(0.55)) + 
  geom_errorbar(width=0.25, linewidth=0.35, position = position_dodge(0.55)) +
  scale_color_manual(values=rev(palette_sex), name="Sex") + 
  theme_bw() + 
  xlab("Diet Traits Derived from UKB Food Frequency Questionnaires") + 
  ylab("Beta (95% CI)") +
  theme(axis.text.x = element_text(angle=90, color="black", size=8, hjust=1, vjust=0.5),
        axis.text.y = element_text(color="black", size=7),
        axis.title = element_text(face="bold", size=10),
        panel.grid = element_blank(),
        panel.grid.major.y = element_line(linewidth=0.1),
        legend.position = "right",
        legend.title = element_text(face="bold", size=8, margin = margin(0,0,2.5,0)), #element_text(face="bold", size=9),
        legend.text = element_text(size=7), #legend.title=element_blank(),legend.position.inside = c(0.99, 0.98),  # Moves legend to top-right inside plot
    #legend.justification.inside = c(1, 1),  # Aligns legend's top-right corner
    legend.background = element_rect(fill = "white", color = "black", linewidth=0.15), 
    legend.key.size = unit(0.5, 'line'),
    legend.margin = margin(1,2,2,1, unit="pt"),
    legend.spacing = unit(2,unit="line"),
    legend.box.margin = margin(0,0,0,-5)
  )

p_diet_bysex %>% ggsave(filename="../data/processed/briefcomm/plot_diet_by_sex_unadj.pdf", height=4, width=6)

```






